spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stack_overflow?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: jeonni
    password: "stack!012"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 550829219732-pgujqpprubj36trf9pdgebe4qd3rctso.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
logging.level:
  org.hibernate.SQL: debug

jwt:
  key: "asdjklhalsdjkhaljsdkhasdjkhasdjkalsdjkajsdkl123412344"
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420